// Catálogo del taller. La FICHA de cada modelo (cajones, puertas, parches) se copió
// de BASE_DATOS_V3 (14/08/2026) como punto de partida: la app la sube UNA vez a la
// base compartida y de ahí en adelante se edita dentro de la app (sección Catálogo).
// Donde la ficha no tenía el dato se deja null y la app dice "falta dato"; no se inventa.
// Los tres modelos que existen en madera y en MDF llevan "MDF" en el nombre.
// No hay ninguna conexión con el programa de producción.
// Guacales compartidos: los modelos con "guacal" usan el mueble pintado del modelo-guacal
// (es_guacal); las puertas son las que hacen el modelo. coloresLisos son los únicos colores
// de muebles y piezas; gruposColor (combinaciones) solo se usa en los pedidos.
window.CATALOGO = {
 "fichas": [
  {
   "id": "M001",
   "nombre": "Mariana Abanico",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M002",
   "nombre": "Mariana África",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M003",
   "nombre": "Mariana Alondra",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M004",
   "nombre": "Mariana Canadá",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 1,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M005",
   "nombre": "Mariana Charly",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 3,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M006",
   "nombre": "Mariana Cisne",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M007",
   "nombre": "Mariana Duela Abatible",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M008",
   "nombre": "Mariana Liso",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 3,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M009",
   "nombre": "Mariana Mariposa",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 3,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 2,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M010",
   "nombre": "Mariana Maya",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M011",
   "nombre": "Mariana México",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M012",
   "nombre": "Mariana Midas",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M013",
   "nombre": "Mariana Mónaco",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 3,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 2,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M014",
   "nombre": "Mariana Óvalo",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M015",
   "nombre": "Mariana Parrilla Gruesa Abatible 6 cajones",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 1,
   "puertas_chicas_luna": 1,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M016",
   "nombre": "Mariana Petaquero Liso",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 3,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M017",
   "nombre": "Mariana Ramas",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M018",
   "nombre": "Mariana Ramas Con caja de seguridad",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M019",
   "nombre": "Mariana Rayas",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 1,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M020",
   "nombre": "Mariana Rejilla Mixta 3 cajones",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 3,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M021",
   "nombre": "Mariana Rejilla Mixta 2 lunas y 4 cajones",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-2-lunas"
  },
  {
   "id": "M022",
   "nombre": "Mariana Rombo",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M023",
   "nombre": "Mariana Sol",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M024",
   "nombre": "Mariana Tablero",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-mariana-3-cajones"
  },
  {
   "id": "M025",
   "nombre": "Monarca Abanico",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M026",
   "nombre": "Monarca África",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M027",
   "nombre": "Monarca Círculo",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": true,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M028",
   "nombre": "Monarca Colonial",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 2,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M029",
   "nombre": "Monarca Duela",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M030",
   "nombre": "Monarca Duela Con lámpara",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 0,
   "total_puertas": 9,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M031",
   "nombre": "Monarca Estrella",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 6,
   "total_puertas": 14,
   "lleva_parches": true,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M032",
   "nombre": "Monarca Liso 2.40",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 8,
   "puertas_chicas_luna": 0,
   "total_puertas": 12,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M033",
   "nombre": "Monarca Liso 2.00",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 8,
   "puertas_chicas_luna": 0,
   "total_puertas": 12,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M034",
   "nombre": "Monarca Liso Con zapatera",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 0,
   "total_puertas": 8,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M035",
   "nombre": "Monarca Mariposa",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 6,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M036",
   "nombre": "Monarca Maya",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 6,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M037",
   "nombre": "Monarca Maya Con lámpara",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 0,
   "total_puertas": 9,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M038",
   "nombre": "Monarca Mediterráneo",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 2,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M039",
   "nombre": "Monarca México",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M040",
   "nombre": "Monarca México Con caja de seguridad",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M041",
   "nombre": "Monarca México Con lámpara",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 0,
   "total_puertas": 9,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M042",
   "nombre": "Monarca Midas",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M043",
   "nombre": "Monarca Midas Con tocador",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 3,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 2,
   "total_puertas": 11,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M044",
   "nombre": "Monarca Midas Con lámpara",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 0,
   "total_puertas": 9,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M045",
   "nombre": "Monarca Mónaco",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 2,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M046",
   "nombre": "Monarca Óvalo",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 2,
   "total_puertas": 12,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M047",
   "nombre": "Monarca Óvalo Con zapatera",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 4,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 4,
   "total_puertas": 14,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M048",
   "nombre": "Monarca Persiana",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 2,
   "total_puertas": 8,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M049",
   "nombre": "Monarca Ramas",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M050",
   "nombre": "Monarca Ramas Con caja de seguridad",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M051",
   "nombre": "Monarca Rejilla Mixta",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M052",
   "nombre": "Monarca Rombo",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M053",
   "nombre": "Monarca Romano",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 2,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M054",
   "nombre": "Monarca Sol",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 2,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M055",
   "nombre": "Monarca Tablero",
   "familia": "Monarca",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 10,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M056",
   "nombre": "Petaquero Abanico Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": true,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M057",
   "nombre": "Petaquero Círculo Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 1,
   "total_puertas": 6,
   "lleva_parches": true,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M058",
   "nombre": "Petaquero Cisne Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 1,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M059",
   "nombre": "Petaquero Colonial Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 1,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M060",
   "nombre": "Petaquero Duela Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M061",
   "nombre": "Petaquero Liso Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 3,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M062",
   "nombre": "Petaquero Mariposa Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M063",
   "nombre": "Petaquero Maya Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M064",
   "nombre": "Petaquero México Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M065",
   "nombre": "Petaquero Midas Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M066",
   "nombre": "Petaquero Óvalo Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 1,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M067",
   "nombre": "Petaquero Ramas Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M068",
   "nombre": "Petaquero Rejilla Mixta Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M069",
   "nombre": "Petaquero Rombo Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M070",
   "nombre": "Petaquero Rombo Multifamiliar con caja de seguridad",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M071",
   "nombre": "Petaquero Tablero Multifamiliar",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true,
   "guacal": "G-petaquero-multi"
  },
  {
   "id": "M072",
   "nombre": "Ropero Casa Blanca",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M073",
   "nombre": "Ropero Deysi",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M074",
   "nombre": "Ropero Deysi Infantil niña",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M075",
   "nombre": "Ropero Deysi Infantil niño",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M076",
   "nombre": "Ropero Elvis",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 2,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M077",
   "nombre": "Ropero Palomo",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": true,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M078",
   "nombre": "Ropero Pinocho",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 1,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M079",
   "nombre": "Ropero Pinocho Sin copete",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 2,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M080",
   "nombre": "Ropero Poliéster",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 4,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M081",
   "nombre": "Ropero Sammy",
   "familia": "Ropero",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M082",
   "nombre": "Cómoda Midas",
   "familia": "Cómoda",
   "tipo": "madera",
   "cajones": 5,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 2,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M083",
   "nombre": "Cómoda Rombo",
   "familia": "Cómoda",
   "tipo": "madera",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 1,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M084",
   "nombre": "Vitrina Angelita",
   "familia": "Vitrina",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 4,
   "total_puertas": 7,
   "lleva_parches": false,
   "lleva_respaldo": true,
   "activo": true
  },
  {
   "id": "M085",
   "nombre": "Vitrina Kukis",
   "familia": "Vitrina",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 4,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 7,
   "lleva_parches": false,
   "lleva_respaldo": true,
   "activo": true
  },
  {
   "id": "M086",
   "nombre": "Cajonera Acapulqueña",
   "familia": "Cajonera",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M087",
   "nombre": "Cajonera Acapulqueña Con luna",
   "familia": "Cajonera",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 3,
   "puertas_chicas_luna": 1,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M088",
   "nombre": "Cajonera Amanda 5 cajones",
   "familia": "Cajonera",
   "tipo": "madera",
   "cajones": 5,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 0,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "M089",
   "nombre": "Cajonera Amanda 10 cajones",
   "familia": "Cajonera",
   "tipo": "madera",
   "cajones": 10,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 0,
   "lleva_parches": false,
   "lleva_respaldo": false,
   "activo": true
  },
  {
   "id": "D001",
   "nombre": "Alacena Delfina Con porta garrafón",
   "familia": "Alacena",
   "tipo": "mdf",
   "cajones": 5,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 1,
   "puertas_chicas_luna": 0,
   "total_puertas": 3,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D002",
   "nombre": "Alacena Midas",
   "familia": "Alacena",
   "tipo": "mdf",
   "cajones": 1,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 4,
   "puertas_chicas_luna": 2,
   "total_puertas": 7,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D003",
   "nombre": "Alacena Pato",
   "familia": "Alacena",
   "tipo": "mdf",
   "cajones": 2,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 2,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D004",
   "nombre": "Alacena Tulipán",
   "familia": "Alacena",
   "tipo": "mdf",
   "cajones": 2,
   "puertas_grandes": 1,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 2,
   "total_puertas": 5,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D005",
   "nombre": "Alacena Vaca",
   "familia": "Alacena",
   "tipo": "mdf",
   "cajones": 2,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 2,
   "total_puertas": 6,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D006",
   "nombre": "Espejo Organizador Vanity",
   "familia": "Espejo",
   "tipo": "mdf",
   "cajones": 2,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 1,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D007",
   "nombre": "Librero Monte Carlos 55 pulgadas",
   "familia": "Librero",
   "tipo": "mdf",
   "cajones": 0,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 8,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D008",
   "nombre": "Librero Monte Carlos 65 pulgadas",
   "familia": "Librero",
   "tipo": "mdf",
   "cajones": 0,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 8,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D009",
   "nombre": "Librero Monte Carlos 75 pulgadas",
   "familia": "Librero",
   "tipo": "mdf",
   "cajones": 0,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 6,
   "puertas_chicas_luna": 0,
   "total_puertas": 8,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D010",
   "nombre": "Monarca Estrella MDF",
   "familia": "Monarca",
   "tipo": "mdf",
   "cajones": 6,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 6,
   "total_puertas": 14,
   "lleva_parches": true,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D011",
   "nombre": "Petaquero Primavera",
   "familia": "Petaquero",
   "tipo": "mdf",
   "cajones": 4,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 4,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 4,
   "total_puertas": 10,
   "lleva_parches": true,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D012",
   "nombre": "Recámara Óvalo",
   "familia": "Recámara",
   "tipo": "mdf",
   "cajones": 3,
   "puertas_grandes": 4,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 2,
   "total_puertas": 8,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D013",
   "nombre": "Ropero Elvis MDF",
   "familia": "Ropero",
   "tipo": "mdf",
   "cajones": 4,
   "puertas_grandes": 0,
   "puertas_grandes_luna": 2,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 2,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D014",
   "nombre": "Ropero Palomo MDF",
   "familia": "Ropero",
   "tipo": "mdf",
   "cajones": 4,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 1,
   "puertas_chicas": 2,
   "puertas_chicas_luna": 0,
   "total_puertas": 5,
   "lleva_parches": true,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D015",
   "nombre": "Ropero San Bernardo",
   "familia": "Ropero",
   "tipo": "mdf",
   "cajones": 0,
   "puertas_grandes": null,
   "puertas_grandes_luna": null,
   "puertas_chicas": null,
   "puertas_chicas_luna": null,
   "total_puertas": null,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D016",
   "nombre": "Tocador Cisne",
   "familia": "Tocador",
   "tipo": "mdf",
   "cajones": 3,
   "puertas_grandes": null,
   "puertas_grandes_luna": null,
   "puertas_chicas": null,
   "puertas_chicas_luna": null,
   "total_puertas": null,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D017",
   "nombre": "Tocador Kitty",
   "familia": "Tocador",
   "tipo": "mdf",
   "cajones": 3,
   "puertas_grandes": null,
   "puertas_grandes_luna": null,
   "puertas_chicas": null,
   "puertas_chicas_luna": null,
   "total_puertas": null,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D018",
   "nombre": "Tocador México",
   "familia": "Tocador",
   "tipo": "mdf",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 0,
   "total_puertas": 2,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "D019",
   "nombre": "Tocador Óvalo",
   "familia": "Tocador",
   "tipo": "mdf",
   "cajones": 3,
   "puertas_grandes": 2,
   "puertas_grandes_luna": 0,
   "puertas_chicas": 0,
   "puertas_chicas_luna": 2,
   "total_puertas": 4,
   "lleva_parches": false,
   "lleva_respaldo": null,
   "activo": true
  },
  {
   "id": "G-mariana-3-cajones",
   "nombre": "Mariana 3 cajones",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 3,
   "puertas_grandes": null,
   "puertas_grandes_luna": null,
   "puertas_chicas": null,
   "puertas_chicas_luna": null,
   "total_puertas": null,
   "lleva_parches": null,
   "lleva_respaldo": null,
   "es_guacal": true,
   "activo": true,
   "nota": "Guacal compartido: sirve para Abanico, Cisne, Duela, Mariposa, Maya, México, Midas, Rombo, Sol, Tablero y Rejilla Mixta 3 cajones. Las puertas hacen el modelo."
  },
  {
   "id": "G-mariana-2-lunas",
   "nombre": "Mariana 2 lunas y 6 cajones",
   "familia": "Mariana",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": null,
   "puertas_grandes_luna": null,
   "puertas_chicas": null,
   "puertas_chicas_luna": null,
   "total_puertas": null,
   "lleva_parches": null,
   "lleva_respaldo": null,
   "es_guacal": true,
   "activo": true,
   "nota": "Guacal compartido: sirve para Círculo y Rejilla Mixta (2 lunas). Las puertas hacen el modelo."
  },
  {
   "id": "G-petaquero-multi",
   "nombre": "Petaquero Multifamiliar 1 pieza",
   "familia": "Petaquero",
   "tipo": "madera",
   "cajones": 6,
   "puertas_grandes": null,
   "puertas_grandes_luna": null,
   "puertas_chicas": null,
   "puertas_chicas_luna": null,
   "total_puertas": null,
   "lleva_parches": null,
   "lleva_respaldo": null,
   "es_guacal": true,
   "activo": true,
   "nota": "Guacal compartido: sirve para todos los Petaqueros Multifamiliar de 1 pieza. Las puertas hacen el modelo."
  }
 ],
 "gruposColor": [
  {
   "grupo": "Negro",
   "colores": [
    "Negro completo",
    "Negro puertas cafés",
    "Negro puertas grises",
    "Negro puertas blancas",
    "Negro puertas rojas",
    "Negro con café",
    "Negro con gris",
    "Negro con blanco",
    "Negro brilloso",
    "Negro parches rojos",
    "Negro parches amarillos",
    "Negro parches cremas",
    "Negro puertas cafés parches cremas",
    "Negro puertas grises parches rojas",
    "Negro puertas grises parches negros"
   ]
  },
  {
   "grupo": "Café",
   "colores": [
    "Café completo",
    "Café puertas blancas",
    "Café con blancas"
   ]
  },
  {
   "grupo": "Gris",
   "colores": [
    "Gris completo",
    "Gris puertas blancas",
    "Gris puertas cafés",
    "Gris con blancas"
   ]
  },
  {
   "grupo": "Blanco",
   "colores": [
    "Blanco completo"
   ]
  },
  {
   "grupo": "Nogal",
   "colores": [
    "Nogal"
   ]
  },
  {
   "grupo": "Especiales",
   "colores": [
    "Iron-Man",
    "Rosa con blanco",
    "Azul con blanco"
   ]
  }
 ],
 "categoriasMaterial": [
  "Cubetas",
  "Tambos"
 ],
 "presentaciones": [
  {
   "n": "Cubeta",
   "l": 19
  },
  {
   "n": "Cubeta",
   "l": 16
  },
  {
   "n": "Tambo",
   "l": 200
  },
  {
   "n": "Galón",
   "l": 4
  },
  {
   "n": "Bote",
   "l": 1
  }
 ],
 "clientes": [
  "Sr. Pedro Orozco",
  "La Principal, Xalapa",
  "Sr. Sabino Ramos",
  "Sr. Edgar Vazquez",
  "Hector De La Rosa",
  "Asociación Mueblera",
  "Muebleria Modelo",
  "Sr. Guillermo Alonso",
  "Sra. Josefina Celis",
  "Sr. Nicolas Zepeda Aguilar",
  "Sr. Octavio Perez, Orizaba",
  "Yanet Orozco",
  "Muebleria Maria Eugenia",
  "Gregorio Zacapa",
  "Muebleria Joma",
  "Muebleria Mydas",
  "Sr. Valerio",
  "Dolores Gomez",
  "Unión Mueblera Poblana",
  "Sr. Alfredo, Lupe Lupita",
  "Guillermo Perez",
  "Sr. Rosendo",
  "Sr. Vela",
  "Sr. Velarde",
  "Sr. Bernabe Garcia",
  "Lorenzo Reyes",
  "Agustin",
  "Carlos Maldonado",
  "Carlos Valera",
  "Clientes Menudeo",
  "Clientes Victor Garcia",
  "Edgar Rosas",
  "Gumaro Lopez",
  "Gustavo Perez",
  "Oscar Rosas",
  "Saul Gomez",
  "Sr. Agustin Rosendo",
  "Sr. Andres Xeguatepec",
  "Sr. Pascual",
  "Sr. Gildardo"
 ],
 "gente": [
  "Brandon",
  "Juan",
  "Antelmo",
  "Raúl",
  "Ángel",
  "Daniel",
  "Jorge",
  "Giovanni",
  "Rafael",
  "Miguel",
  "Luis",
  "Fernando",
  "Hector",
  "Silvia",
  "Antonio",
  "Marisol",
  "Uriel"
 ],
 "arranqueMaterial": [
  {
   "nombre": "LACA INDUSTRIAL NITRO AMARILLO OXIDO",
   "apodos": [
    "laca amarilla"
   ],
   "categoria": "Cubetas",
   "codigo": "13261",
   "barras": "7506180720880",
   "presentacion": "Cubeta",
   "litros": 19
  },
  {
   "nombre": "CF-6040 CATALIZADOR",
   "apodos": [
    "catalizador"
   ],
   "categoria": "Cubetas",
   "marca": "HiCoat",
   "codigo": "521160406",
   "barras": "7501456603560",
   "presentacion": "Cubeta",
   "litros": 19
  },
  {
   "nombre": "HICEL FONDO TRANSPARENTE DELICIAS",
   "apodos": [
    "fondo transparente"
   ],
   "categoria": "Cubetas",
   "marca": "HiCel",
   "codigo": "514470606",
   "barras": "7501456620420",
   "presentacion": "Cubeta",
   "litros": 19
  },
  {
   "nombre": "BARNIZ PU BLANCO ESTABLE ALTO BRILLO",
   "apodos": [
    "barniz blanco"
   ],
   "categoria": "Cubetas",
   "codigo": "E-68131",
   "barras": "7506180720521",
   "presentacion": "Cubeta",
   "litros": 16
  },
  {
   "nombre": "MEZCLA DIM-500",
   "apodos": [
    "thinner"
   ],
   "categoria": "Tambos",
   "marca": "Diluyentes y Mezclas",
   "codigo": "",
   "barras": "",
   "presentacion": "Tambo",
   "litros": null
  },
  {
   "nombre": "DIM NEGRO",
   "apodos": [
    "pintura negra"
   ],
   "categoria": "Cubetas",
   "marca": "Diluyentes y Mezclas",
   "codigo": "",
   "barras": "",
   "presentacion": "Cubeta",
   "litros": null
  }
 ],
 "coloresLisos": [
  "Negro",
  "Negro brilloso",
  "Café",
  "Gris",
  "Blanco",
  "Nogal",
  "Rojo",
  "Crema",
  "Amarillo",
  "Azul",
  "Rosa",
  "Naranja"
 ]
};
